
services:
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: postgres
    restart: unless-stopped
    networks:
      - dokploy-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERPASS}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: ${TZ}
    command: >
      postgres
        -c wal_level=logical
        -c shared_preload_libraries=pg_stat_statements,pgaudit,pg_cron,auto_explain
        -c pgaudit.log=ddl
        -c log_connections=on
        -c log_disconnections=on
        -c log_line_prefix='%m [%p] user=%u db=%d app=%a client=%h '
        -c cron.database_name=${POSTGRES_DB}
        -c max_wal_size=2GB
    volumes:
      - ${PG_DATA_HOST_DIR:-../files/volumes/db}:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "${POSTGRES_SUPERUSER}", "-d", "${POSTGRES_DB}", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 18
      start_period: 90s
    labels:
      - logging=alloy
      - service=postgres
      - env=${ENVIRONMENT:-dev}
      - org=peakstone

  # One-off Postgres bootstrap: creates roles, grants, and sets passwords
  db-bootstrap:
    image: postgres:17
    container_name: db-bootstrap
    networks:
      - dokploy-network
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/bash", "/scripts/db-bootstrap.sh"]
    restart: "no"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      PGPASSWORD: ${POSTGRES_SUPERPASS}
      DB_AUTHENTICATOR_PASSWORD: ${DB_AUTHENTICATOR_PASSWORD}
      HASURA_DB_PASSWORD: ${HASURA_DB_PASSWORD}
      DB_MIGRATOR_PASSWORD: ${DB_MIGRATOR_PASSWORD}
    volumes:
      - ./scripts:/scripts:ro

  pgcat:
    image: ${PGCAT_IMAGE:-ghcr.io/postgresml/pgcat:latest}
    container_name: pgcat
    restart: unless-stopped
    networks:
      - dokploy-network
    depends_on:
      postgres:
        condition: service_healthy
    command: ["pgcat", "/etc/pgcat.toml"]
    volumes:
      - ${PGCAT_CONFIG_PATH:-../files/volumes/pgcat.toml}:/etc/pgcat.toml:ro
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/6432' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      - logging=alloy
      - service=pooler
      - env=${ENVIRONMENT:-dev}
      - org=peakstone

  postgrest:
    image: postgrest/postgrest:v12.2.3
    container_name: postgrest
    restart: unless-stopped
    networks:
      - dokploy-network
    depends_on:
      postgres:
        condition: service_healthy
      pgcat:
        condition: service_started
      db-bootstrap:
        condition: service_completed_successfully
      atlas-migrate:
        condition: service_completed_successfully
    environment:
      PGRST_DB_URI: 'host=pgcat port=6432 dbname=${POSTGRES_DB} user=db_authenticator password=${DB_AUTHENTICATOR_PASSWORD}'
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMAS: public,common,people,pipeline,activities,leads,docs
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_ROLE_CLAIM_KEY: .role
      PGRST_DB_PREPARED_STATEMENTS: "false"
      PGRST_OPENAPI_SERVER_PROXY_URI: https://${DOMAIN_API}
    labels:
      - logging=alloy
      - service=api
      - env=${ENVIRONMENT:-dev}
      - org=peakstone

  hasura:
    image: hasura/graphql-engine:v2.40.0-ce
    container_name: hasura
    restart: unless-stopped
    networks:
      - dokploy-network
    depends_on:
      postgres:
        condition: service_healthy
      pgcat:
        condition: service_started
      db-bootstrap:
        condition: service_completed_successfully
      atlas-migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/healthz >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_METADATA_DATABASE_URL: ${HASURA_GRAPHQL_METADATA_DATABASE_URL:-${HASURA_GRAPHQL_DATABASE_URL}}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: web_anon
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup,http-log,websocket-log,query-log
      HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES: "true"
      HASURA_GRAPHQL_CORS_DOMAIN: ${HASURA_CORS}
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_JWT_SECRET: >
        {"type":"HS256","key":"${JWT_SECRET}","claims_namespace_path":"$","claims_format":"json"}
    labels:
      - logging=alloy
      - service=graphql
      - env=${ENVIRONMENT:-dev}
      - org=peakstone

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: pgadmin
    restart: unless-stopped
    networks:
      - dokploy-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost/misc/ping >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 10s
      start_period: 60s
      retries: 5
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    

  minio:
    image: ${MINIO_IMAGE:-minio/minio:latest}
    container_name: minio
    restart: unless-stopped
    networks:
      - dokploy-network
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASS}
    volumes:
      - ${MINIO_DATA_HOST_DIR:-../files/volumes/storage/minio_data}:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9000/minio/health/live >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - logging=alloy
      - service=storage
      - env=${ENVIRONMENT:-dev}
      - org=peakstone

  # One-off MinIO bootstrap: creates bucket + policy
  minio-init:
    image: ${MINIO_MC_IMAGE:-minio/mc:latest}
    container_name: minio-init
    networks:
      - dokploy-network
    depends_on:
      minio:
        condition: service_started
    entrypoint: ["/bin/sh","/init/minio-init.sh"]
    restart: "no"
    environment:
      MINIO_ALIAS: ${MINIO_ALIAS:-minio}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASS: ${MINIO_ROOT_PASS}
      MINIO_BUCKET: ${MINIO_BUCKET}
      S3_APP_ACCESS_KEY: ${S3_APP_ACCESS_KEY}
      S3_APP_SECRET_KEY: ${S3_APP_SECRET_KEY}
      # Loki dedicated credentials (optional; enables least-privilege user/policy)
      LOKI_ACCESS_KEY: ${LOKI_ACCESS_KEY}
      LOKI_SECRET_KEY: ${LOKI_SECRET_KEY}
    volumes:
      - ./minio/init:/init:ro

  # One-off Atlas migrations apply (runs before app services)
  atlas-migrate:
    image: arigaio/atlas:latest
    container_name: atlas-migrate
    networks:
      - dokploy-network
    depends_on:
      postgres:
        condition: service_healthy
      db-bootstrap:
        condition: service_completed_successfully
    working_dir: /workspace/atlas
    command: ["migrate", "apply", "--dir", "file://migrations", "--url", "${ATLAS_URL}", "--allow-dirty"]
    restart: "no"
    environment:
      ATLAS_URL: ${ATLAS_URL}
    volumes:
      - ./atlas:/workspace/atlas:ro

  imgproxy:
    image: darthsim/imgproxy:v3.8.0
    container_name: imgproxy
    restart: unless-stopped
    networks:
      - dokploy-network
    environment:
      IMGPROXY_KEY: ${IMGPROXY_KEY_HEX}
      IMGPROXY_SALT: ${IMGPROXY_SALT_HEX}
      IMGPROXY_BASE_URL: ${IMGPROXY_BASE_URL}
      IMGPROXY_ALLOWED_SOURCES: ${IMGPROXY_ALLOWED_SOURCES}
      IMGPROXY_ENABLE_WEBP_DETECTION: "true"
      IMGPROXY_MAX_SRC_RESOLUTION: "80"
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    networks:
      - dokploy-network
    command: ["run","--server.http.listen-addr=0.0.0.0:12345","--storage.path=/var/lib/alloy/data","/etc/alloy/config.alloy"]
    volumes:
      - ./logging/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy_data:/var/lib/alloy/data
    depends_on:
      loki:
        condition: service_started
    expose:
      - "12345"

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: ["-config.file=/etc/loki/loki-config.yml"]
    networks:
      - dokploy-network
    user: "0:0"
    environment:
      AWS_ACCESS_KEY_ID: ${LOKI_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${LOKI_SECRET_KEY}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-http://minio:9000}
    volumes:
      - ./logging/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/var/loki
    depends_on:
      minio:
        condition: service_started

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    networks:
      - dokploy-network
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./logging/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      loki:
        condition: service_started

networks:
  dokploy-network:
    external: true

volumes:
  pgadmin_data:
  alloy_data:
  loki_data:
  grafana_data:
