server:
  http_listen_port: 3100
  grpc_listen_port: 9096

auth_enabled: false

schema_config:
  configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  aws:
    # Use env vars AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY / AWS_REGION
    endpoint: ${MINIO_ENDPOINT:-minio:9000}
    s3forcepathstyle: true
    insecure: true
    bucketnames: loki

compactor:
  working_directory: /var/loki/compactor
  compaction_interval: 5m
  delete_request_cancel_period: 24h
  retention_enabled: true

limits_config:
  retention_period: 168h   # 7 days; adjust later
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  max_streams_per_user: 0

chunk_store_config:
  max_look_back_period: 168h
